[package]
name = "ams"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
copypasta = "0.10.2"
dialoguer = "0.11.0"
dotenv = "0.15.0"
serde_json = "1.0.140"
walkdir = "2.5.0"
